### ISSUE TITLE
unable to access extension registry brackets In mac

### ISSUE THREAD

**Issue by MidiaBa** [brackets-archive/bracketsIssues#14882]
I can not access the plugins in bracket in any way. Can anyone help me?

**Comment by abose** [comment]
Hi @MidiaBa Thanks for reaching out. We are aware of the issue and will shortly release a new version of brackets that should work. 
Brackets recently transitioned to the brackets community from adobe, and the repository lives here: https://github.com/brackets-cont/brackets

* Closing as this repository is only an archive of old brackets issues. 
* Please Track the specific issue here: https://github.com/brackets-cont/brackets/issues/37
