### ISSUE TITLE
unable to access the extension registry brackets

### ISSUE THREAD

**Issue by mehedishubho** [brackets-archive/bracketsIssues#14881]
I can't use the extension registry from brackets. isn't showing "unable to access the extension registry, please try again"
what can I do now to solve this issue?
![Screenshot_1](https://user-images.githubusercontent.com/35875394/139720009-c484714c-9267-4f16-a57e-e6026e146173.png)

**Comment by abose** [comment]
Hi @mehedishubho Thanks for reaching out. We are aware of the issue and will shortly release a new version of brackets that should work. 
Brackets recently transitioned to the brackets community from adobe, and the repository lives here: https://github.com/brackets-cont/brackets

* Closing as this repository is only an archive of old brackets issues. 
* Please Track the specific issue here: https://github.com/brackets-cont/brackets/issues/37
